# Generated by Django 5.0.3 on 2024-03-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0002_predio_numero_alter_predio_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='rua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro'),
        ),
    ]
